### ISSUE TITLE
is NimiqWrapper still work ?

### ISSUE THREAD

**Issue by athlona64** [MatthewDLudwig/NimiqWrapper#3]
i'm not sure something wrong but right now is not mining

**Comment by MatthewDLudwig** [comment]
Sorry for missing this issue, the wrapper does indeed still work and just underwent a massive upgrade.  The previous version ran into some issues due to me not keeping up with some of the changes that occurred over the past year, but the new version fixes those issues and should be easier to use as well.

The  default pool for the old version of NimiqWrapper also closed down a few months ago so that could be one reason your miner stopped working.  Feel free to open a new issue if you have any problems with the new version of the wrapper!
